final imageUrl = {
  "facebook":
      "https://cdn1.iconfinder.com/data/icons/social-media-2285/512/Colored_Facebook3_svg-512.png",
  "instagram":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Instagram_colored_svg_1-128.png",
  "twitter":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Twitter3_colored_svg-128.png",
  "messenger":
      "https://cdn4.iconfinder.com/data/icons/social-media-2285/1024/logo-128.png",
  "pinterest":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Pinterest_colored_svg-128.png",
  "linkedin":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Linkedin_unofficial_colored_svg-128.png",
  "slack":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Slack_colored_svg-128.png",
  "reddit":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Reddit3_colored_svg-128.png",
  "twitch":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Twitch_colored_svg-128.png",
  "snapchat":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Snapchat_colored_svg-128.png",
  "behance":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Behance2_glyph_svg-128.png",
  "vimeo":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Vimeo_colored_svg-128.png",
  "dribbble":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Dribbble_colored_svg-128.png",
  "tumblr":
      "https://cdn3.iconfinder.com/data/icons/social-media-2285/512/Tumblr_colored_svg-128.png",
  "medium":
      "https://cdn2.iconfinder.com/data/icons/social-media-2285/512/1_Medium2_glyph_svg-128.png",
  "amazon":
      "https://cdn0.iconfinder.com/data/icons/most-usable-logos/120/Amazon-128.png",
  "apple":
      "https://cdn3.iconfinder.com/data/icons/picons-social/57/56-apple-128.png",
  "google":
      "https://cdn4.iconfinder.com/data/icons/socialcones/508/Google-128.png",
  "soundcloud":
      "https://cdn1.iconfinder.com/data/icons/lumin-social-media-icons/512/Soundcloud-128.png",
  "microsoft":
      "https://cdn4.iconfinder.com/data/icons/social-media-logos-6/512/78-microsoft-128.png",
  "flipkart":
      "https://cdn2.iconfinder.com/data/icons/social-icons-color/512/flipkart-128.png",
  "spotify":
      "https://cdn0.iconfinder.com/data/icons/lumin-social-media-icons/512/Spotify-128.png",
  "netflix":
      "https://cdn4.iconfinder.com/data/icons/social-media-logos-6/512/64-netflix-128.png",
  "rss":
      "https://cdn4.iconfinder.com/data/icons/social-media-logos-6/512/43-rss-128.png",
  "steam":
      "https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_steam-128.png",
  "github":
      "https://cdn4.iconfinder.com/data/icons/social-media-logos-6/512/71-github-128.png",
  "skype":
      "https://cdn2.iconfinder.com/data/icons/social-icons-33/128/Skype-128.png",
  "discord":
      "https://cdn0.iconfinder.com/data/icons/free-social-media-set/24/discord-128.png",
  "wordpress":
      "https://cdn2.iconfinder.com/data/icons/social-media-and-payment/64/-58-128.png",
  "blogger":
      "https://cdn4.iconfinder.com/data/icons/socialcones/508/Blogger-128.png",
  "airbnb":
      "https://cdn3.iconfinder.com/data/icons/social-media-2169/24/social_media_social_media_logo_airbnb-128.png",
  "stackoverflow":
      "https://cdn4.iconfinder.com/data/icons/socialcones/508/StackOverflow-128.png",
  "others":
      "https://cdn4.iconfinder.com/data/icons/internet-security-flat-2/32/Internet_Security_shield_antivirus_protect_lock_locked-128.png"
};

final tags = [
  "facebook",
  "instagram",
  "twitter",
  "messenger",
  "pinterest",
  "linkedin",
  "slack",
  "reddit",
  "twitch",
  "snapchat",
  "behance",
  "vimeo",
  "dribbble",
  "tumblr",
  "medium",
  "amazon",
  "apple",
  "google",
  "soundcloud",
  "microsoft",
  "flipkart",
  "spotify",
  "netflix",
  "rss",
  "steam",
  "github",
  "skype",
  "discord",
  "wordpress",
  "blogger",
  "airbnb",
  "stackoverflow",
  "others"
];
